In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modeling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
## Split the data in training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
# Save the encoders and scaler for later use
with open('label_encoder_gender_regression.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo_regression.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler_regression.pkl', 'wb') as file:
    pickle.dump(scaler, file)

## ANN Regression Problem statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

2024-11-19 14:48:08.186246: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [13]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

/Users/arvindprabakar/Documents/NonAcademic/Courses/GenAI/ANN_Project_Implementation/venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Set up Early Stopping

early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 100663.2969 - mae: 100663.2969 - val_loss: 98496.5547 - val_mae: 98496.5547
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99775.3203 - mae: 99775.3203 - val_loss: 96716.4766 - val_mae: 96716.4766
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 97224.5938 - mae: 97224.5938 - val_loss: 92123.9141 - val_mae: 92123.9141
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 93323.3203 - mae: 93323.3203 - val_loss: 84479.0078 - val_mae: 84479.0078
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 83331.0469 - mae: 83331.0469 - val_loss: 75038.9219 - val_mae: 75038.9219
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 73516.7109 - mae: 73516.7109 - val_loss: 65804.6406 - val_mae: 65804.6406
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 64861.6289 - mae: 64861.6289 - val_loss: 58530.5859 - val_mae: 58530.5859
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 57528.6406 - mae: 57528.6406 - val_loss: 53927.9062 - val_mae: 53927.9062
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53966.5430 - mae: 53966.5430 - val_loss: 51842.3555 - val_mae: 51842.3555
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 51988.5625 - mae: 51988.5625 - val_loss: 51104.6562 - val_mae: 51104.6562
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50696.1680 - mae: 50696.1680 - val_loss: 50887.0977 - val_mae: 50887.0977
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49925.4648 - mae: 49925.4648 - val_loss: 50822.3242 - val_mae: 50822.3242
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50706.0625 - mae: 50706.0625 - val_loss: 50780.3438 - val_mae: 50780.3438
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49729.9805 - mae: 49729.9805 - val_loss: 50741.8281 - val_mae: 50741.8281
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49404.2148 - mae: 49404.2148 - val_loss: 50693.4805 - val_mae: 50693.4805
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49500.5625 - mae: 49500.5625 - val_loss: 50653.6523 - val_mae: 50653.6523
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49720.3867 - mae: 49720.3867 - val_loss: 50630.7617 - val_mae: 50630.7617
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50438.6562 - mae: 50438.6562 - val_loss: 50611.4297 - val_mae: 50611.4297
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50010.3594 - mae: 50010.3594 - val_loss: 50586.5195 - val_mae: 50586.5195
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50131.6484 - mae: 50131.6484 - val_loss: 50566.6953 - val_mae: 50566.6953
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49907.2266 - mae: 49907.2266 - val_loss: 50553.6641 - val_mae: 50553.6641
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49768.2812 - mae: 49768.2812 - val_loss: 50534.9609 - val_mae: 50534.9609
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49738.0352 - mae: 49738.0352 - val_loss: 50526.8789 - val_mae: 50526.8789
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49815.3086 - mae: 49815.3086 - val_loss: 50509.7695 - val_mae: 50509.7695
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49740.0234 - mae: 49740.0234 - val_loss: 50496.1914 - val_mae: 50496.1914
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49416.7461 - mae: 49416.7461 - val_loss: 50488.0000 - val_mae: 50488.0000
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50236.9922 - mae: 50236.9922 - val_loss: 50477.7305 - val_mae: 50477.7305
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49447.9844 - mae: 49447.9844 - val_loss: 50467.0938 - val_mae: 50467.0938
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49589.1016 - mae: 49589.1016 - val_loss: 50469.4570 - val_mae: 50469.4570
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49671.6016 - mae: 49671.6016 - val_loss: 50460.4023 - val_mae: 50460.4023
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48994.7266 - mae: 48994.7266 - val_loss: 50444.2812 - val_mae: 50444.2812
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50058.1797 - mae: 50058.1797 - val_loss: 50447.8906 - val_mae: 50447.8906
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50617.5547 - mae: 50617.5547 - val_loss: 50435.4258 - val_mae: 50435.4258
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50023.4648 - mae: 50023.4648 - val_loss: 50430.6836 - val_mae: 50430.6836
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50110.8594 - mae: 50110.8594 - val_loss: 50422.8750 - val_mae: 50422.8750
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49066.6445 - mae: 49066.6445 - val_loss: 50425.4922 - val_mae: 50425.4922
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50015.3477 - mae: 50015.3477 - val_loss: 50426.0352 - val_mae: 50426.0352
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49379.3008 - mae: 49379.3008 - val_loss: 50431.2188 - val_mae: 50431.2188
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50320.9688 - mae: 50320.9688 - val_loss: 50422.0469 - val_mae: 50422.0469
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50279.4805 - mae: 50279.4805 - val_loss: 50413.1016 - val_mae: 50413.1016
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49874.0742 - mae: 49874.0742 - val_loss: 50409.8125 - val_mae: 50409.8125
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49521.3242 - mae: 49521.3242 - val_loss: 50404.9453 - val_mae: 50404.9453
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49557.0547 - mae: 49557.0547 - val_loss: 50406.1367 - val_mae: 50406.1367
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49286.7578 - mae: 49286.7578 - val_loss: 50411.0625 - val_mae: 50411.0625
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49837.7969 - mae: 49837.7969 - val_loss: 50412.2461 - val_mae: 50412.2461
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49521.4844 - mae: 49521.4844 - val_loss: 50402.7773 - val_mae: 50402.7773
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49392.3164 - mae: 49392.3164 - val_loss: 50393.6836 - val_mae: 50393.6836
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49547.0430 - mae: 49547.0430 - val_loss: 50392.6133 - val_mae: 50392.6133
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49360.0664 - mae: 49360.0664 - val_loss: 50405.3711 - val_mae: 50405.3711
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49169.3125 - mae: 49169.3125 - val_loss: 50391.8867 - val_mae: 50391.8867
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49839.2227 - mae: 49839.2227 - val_loss: 50392.4258 - val_mae: 50392.4258
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49907.2695 - mae: 49907.2695 - val_loss: 50391.6406 - val_mae: 50391.6406
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49046.9727 - mae: 49046.9727 - val_loss: 50386.5469 - val_mae: 50386.5469
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49603.6055 - mae: 49603.6055 - val_loss: 50381.3359 - val_mae: 50381.3359
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49620.5039 - mae: 49620.5039 - val_loss: 50376.8164 - val_mae: 50376.8164
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49210.4961 - mae: 49210.4961 - val_loss: 50386.4062 - val_mae: 50386.4062
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49114.6211 - mae: 49114.6211 - val_loss: 50386.9844 - val_mae: 50386.9844
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49861.3047 - mae: 49861.3047 - val_loss: 50375.8125 - val_mae: 50375.8125
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49396.0977 - mae: 49396.0977 - val_loss: 50385.0625 - val_mae: 50385.0625
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49211.3594 - mae: 49211.3594 - val_loss: 50373.5352 - val_mae: 50373.5352
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49515.1875 - mae: 49515.1875 - val_loss: 50380.0039 - val_mae: 50380.0039
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49271.6133 - mae: 49271.6133 - val_loss: 50371.0781 - val_mae: 50371.0781
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49472.1016 - mae: 49472.1016 - val_loss: 50369.1367 - val_mae: 50369.1367
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49609.2344 - mae: 49609.2344 - val_loss: 50381.8516 - val_mae: 50381.8516
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49464.4922 - mae: 49464.4922 - val_loss: 50378.2969 - val_mae: 50378.2969
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49224.4297 - mae: 49224.4297 - val_loss: 50375.0703 - val_mae: 50375.0703
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49372.9102 - mae: 49372.9102 - val_loss: 50382.0859 - val_mae: 50382.0859
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49202.0977 - mae: 49202.0977 - val_loss: 50378.9766 - val_mae: 50378.9766
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49416.4609 - mae: 49416.4609 - val_loss: 50382.2422 - val_mae: 50382.2422
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49563.1133 - mae: 49563.1133 - val_loss: 50374.8477 - val_mae: 50374.8477
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49362.2227 - mae: 49362.2227 - val_loss: 50370.4688 - val_mae: 50370.4688
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49669.8984 - mae: 49669.8984 - val_loss: 50380.7695 - val_mae: 50380.7695
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49610.1289 - mae: 49610.1289 - val_loss: 50388.9336 - val_mae: 50388.9336

In [19]:

%load_ext tensorboard
%tensorboard --logdir regressionlogs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 85077), started 0:01:52 ago. (Use '!kill 85077' to kill it.)